version: '3.3'
services:
  filebank:
    command: bash -c "./wait-for-it.sh -t 10 localstack:4566 && npm test"
    environment:
      NODE_ENV: test
      S3_ENDPOINT: http://localstack:4566

  mongo:
    ports:
    - 27017:27017

  localstack:
    image: localstack/localstack-light
    environment:
      SERVICES: s3
      DEFAULT_REGION: eu-west-1
    ports:
    - 4566:4566