version: '3.3'
services:
  filebank:
    build: .
    image: hannikkala/filebank
    environment:
      - MONGODB_URL=mongodb://mongo:27017/filebank
    ports:
      - 8000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:3
    expose:
      - 27017
