name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print version number
      run: cd api && node -p "require('./package.json').version"
    - name: Build the Docker image
      run: cd api && npm run build:docker
    - name: Run tests
      run: cd api && npm run test:docker
