name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd api && npm run build:docker
    - name: Run tests
      run: cd api && npm run test:docker
    - name: Tag Docker image
      run: cd api && docker tag hannikkala/filebank:latest hannikkala/filebank:`node -p "require('./package.json').version"`